function [I_row,I_col] = identify_rc_topology_changes()

%created 16/5/16
%last edit 16/5/16

%with model loop through all connections that can be broken. Compare
%between data observed and generated by breaking connections

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

rng(1234)
%need to access Hellinger distance, have copied function across

%set params
params.end_time = 5;
params.dt = 0.1;
params.production_rate=0;
params.flow_rate=1;
params.thin_results = 50;
params.save_name = 'coarse-grained-NCs-ctmc-model';
params.store_output = 0;
params.connections_to_break = [2, 4]; %ie don't break anything

%generate fake data
%(mapping real data to correct NCs will be difficult
initial_distn = 1/16*ones(1,16);
raw_data = ctmc_analysis(initial_distn,params);
%peturb the data with some noise
%raw_data = raw_data+0.05*rand(size(raw_data))

%now in model loop through all possible connections, break these and
%compare the distances of distns from raw data
%currently loops over everything, even if no connection present
score = zeros(16);
for i=1:16
    for j=1:16
        params.connections_to_break=[i, j];
        d_prime = ctmc_analysis(initial_distn,params);
        
        score(i,j) = norm(raw_data-d_prime,2); %store distance between data, can try different distance metrics
    end
end

[~,I] = min(score(:));
[I_row, I_col] = ind2sub(size(score),I);

fprintf('Results suggest that data was generated with connections between %d and %d broken. \n',I_row,I_col);
